POST http://localhost:8000/apis/user/register/
Content-Type: application/json

{"first_name": "Motiur Rahman", "last_name": "Mizan", "phone_num": "+880 1315 243425", "university": "Dhaka University", "email": "info@howtodsa.com", "password": "password"}
###

POST http://localhost:8000/apis/user/login/
Content-Type: application/json

{"email": "mrmizan@howtodsa.com", "password": "password"}
###

GET http://localhost:8000/apis/user/test_token/
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b

###

POST http://localhost:8000/apis/user/logout/
Authorization: Token 5bd4ff48401036136defcb4930109588191bcfe1

###


GET http://localhost:8000/apis/user/get_user_info/
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b

###


POST http://localhost:8000/apis/vocab/add_vocab/
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b
Content-Type: application/json

{"word": "fantasy", "owner": 1, "meanings": [{"meaning": "উদ্ভট কল্পনা"}, {"meaning": "কাল্পনিক "}]}
###


GET http://localhost:8000/apis/vocab/check_vocab/?word=fantasy
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b
Content-Type: application/json
###

GET http://localhost:8000/apis/vocab/get_user_vocabs/?page=2
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b
Content-Type: application/json

###


GET http://localhost:8000/apis/vocab/get_an_MCQ/?to_from=b2e
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b
Content-Type: application/json
###


GET http://localhost:8000/apis/vocab/get_N_MCQs/?N=5&to_from=b2e
Authorization: Token 446c166174ae2379bd31fafa5a3f537c6f3d839b
Content-Type: application/json
###