# Generated by Django 5.1.2 on 2024-11-04 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=557)),
                ('vocab_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
