# Generated by Django 5.1.2 on 2024-11-06 09:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_alter_word_word'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_word_per_owner',
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('word', 'owner')},
        ),
    ]
